version: "3.7"

# docker swarm init --advertise-addr 127.0.0.1
services:
  # server:
  #   image: xxx/server:latest
  #   build: ./server
  #   ports:
  #     - "3000:3000"
  # client:
  #   image: xxx/client:latest
  #   build: ./app
  #   ports:
  #     - "8080:8080"

  # Use root/pl,okm123 as user/password credentials
  mysql:
    image: mysql
    volumes:
      - type: volume
        source: sqldata
        target: /var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "pl,okm123"

  redis:
    image: redis
    volumes:
      - type: volume
        source: redisdata
        target: /data
    ports:
      - "6379:6379"

  mongoDB:
    image: mongo
    volumes:
      - type: volume
        source: mongodata
        target: /data/db
    ports:
      - "27017:27017"
volumes:
  mysqldata:
  redisdata:
  mongodata:
